# Generated by Django 2.1.7 on 2019-03-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('briskula', '0004_auto_20190323_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uporabniki',
            name='turnir',
        ),
        migrations.AddField(
            model_name='uporabniki',
            name='turnir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='briskula.Turnir'),
            preserve_default=False,
        ),
    ]
