# Generated by Django 2.1.7 on 2019-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briskula', '0006_auto_20190323_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnir',
            name='drugi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='turnir',
            name='prvi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='turnir',
            name='tretji',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
